# Generated by Django 3.0 on 2022-03-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO profiles_profile SELECT * FROM oc_lettings_site_profile;"
        ),
        migrations.RunSQL(
            "DROP TABLE oc_lettings_site_profile;"
        )
    ]
