# Generated by Django 3.0 on 2022-03-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO lettings_letting SELECT * FROM oc_lettings_site_letting;"
        ),
        migrations.RunSQL(
            "INSERT INTO lettings_address SELECT * FROM oc_lettings_site_address;"
        ),
        migrations.RunSQL(
            "DROP TABLE oc_lettings_site_address;"
        ),
        migrations.RunSQL(
            "DROP TABLE oc_lettings_site_letting;"
        )
    ]
